test:
	python3 test/test_preprocessing.py
	python3 test/test_processing.py
	python3 test/test_postprocessing.py
# Install dependencies
prereqs:
	python3 -m pip  install --upgrade pip
	pip  install -r requirements.txt
	python3 -m py_compile src/preprocessing.py 

# Build step (if needed)
build:
	python3 -m py_compile src/processing.py 

# Run all tests
