name: Prereqs + Build

# Run the workflow on push and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: make prereqs -f Makefile.docker

      # Build the project
      - name: Build project
        run: make build -f Makefile.docker
